export type SeedBrand = { name: string; slug: string };

export type SeedCategory = {
  description?: string;
  icon?: string;
  name: string;
  parent?: string;
  slug: string;
  sortOrder: number;
};

export type SeedAttributeType =
  "text" | "number" | "boolean" | "select" | "multiselect" | "range";

export type SeedAttribute = {
  isFilterable: boolean;
  isVariantOption: boolean;
  name: string;
  options?: readonly string[];
  slug: string;
  sortOrder: number;
  type: SeedAttributeType;
  unit?: string;
};

export type SeedProduct = {
  attributes?: Record<string, string | number | boolean>;
  brand: string;
  category: string;
  compareAt?: number;
  description: string;
  name: string;
  popularity?: number;
  price: number;
  rating?: number;
  ratingCount?: number;

  stock?: number | readonly number[];
  variantAttribute?: string;
  variantValues?: readonly string[];
};

export const seedBrands: readonly SeedBrand[] = [
  { name: "Apple", slug: "apple" },
  { name: "Samsung", slug: "samsung" },
  { name: "Tecno", slug: "tecno" },
  { name: "Infinix", slug: "infinix" },
  { name: "Xiaomi", slug: "xiaomi" },
  { name: "HP", slug: "hp" },
  { name: "Dell", slug: "dell" },
  { name: "Lenovo", slug: "lenovo" },
  { name: "Asus", slug: "asus" },
  { name: "LG", slug: "lg" },
  { name: "Hisense", slug: "hisense" },
  { name: "Sony", slug: "sony" },
  { name: "JBL", slug: "jbl" },
  { name: "Anker", slug: "anker" },
  { name: "Logitech", slug: "logitech" },
  { name: "Microsoft", slug: "microsoft" },
  { name: "Nike", slug: "nike" },
  { name: "Adidas", slug: "adidas" },
  { name: "Zara", slug: "zara" },
  { name: "Ikea", slug: "ikea" },
  { name: "Binatone", slug: "binatone" },
  { name: "Nivea", slug: "nivea" },
  { name: "The Ordinary", slug: "the-ordinary" },
  { name: "Decathlon", slug: "decathlon" },
];

export const seedCategories: readonly SeedCategory[] = [
  { name: "Electronics", slug: "electronics", sortOrder: 1, icon: "tv" },
  { name: "Computing", slug: "computing", sortOrder: 2, icon: "laptop" },
  { name: "Gaming", slug: "gaming", sortOrder: 3, icon: "gamepad-2" },
  { name: "Fashion", slug: "fashion", sortOrder: 4, icon: "shirt" },
  { name: "Furniture", slug: "furniture", sortOrder: 5, icon: "armchair" },
  { name: "Home & Appliances", slug: "home-appliances", sortOrder: 6, icon: "house" },
  { name: "Beauty", slug: "beauty", sortOrder: 7, icon: "sparkles" },
  { name: "Sports", slug: "sports", sortOrder: 8, icon: "dumbbell" },

  {
    name: "Phones & Tablets",
    slug: "phones-tablets",
    parent: "electronics",
    sortOrder: 1,
  },
  { name: "Audio", slug: "audio", parent: "electronics", sortOrder: 2 },
  { name: "Televisions", slug: "televisions", parent: "electronics", sortOrder: 3 },
  { name: "Laptops", slug: "laptops", parent: "computing", sortOrder: 1 },
  { name: "Monitors", slug: "monitors", parent: "computing", sortOrder: 2 },
  {
    name: "Computer Accessories",
    slug: "computer-accessories",
    parent: "computing",
    sortOrder: 3,
  },
  { name: "Consoles", slug: "consoles", parent: "gaming", sortOrder: 1 },
  {
    name: "Gaming Accessories",
    slug: "gaming-accessories",
    parent: "gaming",
    sortOrder: 2,
  },
  { name: "Men's Clothing", slug: "mens-clothing", parent: "fashion", sortOrder: 1 },
  {
    name: "Women's Clothing",
    slug: "womens-clothing",
    parent: "fashion",
    sortOrder: 2,
  },
  { name: "Footwear", slug: "footwear", parent: "fashion", sortOrder: 3 },
  {
    name: "Office Furniture",
    slug: "office-furniture",
    parent: "furniture",
    sortOrder: 1,
  },
  { name: "Living Room", slug: "living-room", parent: "furniture", sortOrder: 2 },
  {
    name: "Kitchen Appliances",
    slug: "kitchen-appliances",
    parent: "home-appliances",
    sortOrder: 1,
  },
  { name: "Home Care", slug: "home-care", parent: "home-appliances", sortOrder: 2 },
  { name: "Skincare", slug: "skincare", parent: "beauty", sortOrder: 1 },
  { name: "Fragrance", slug: "fragrance", parent: "beauty", sortOrder: 2 },
  {
    name: "Fitness Equipment",
    slug: "fitness-equipment",
    parent: "sports",
    sortOrder: 1,
  },
  { name: "Sportswear", slug: "sportswear", parent: "sports", sortOrder: 2 },

  { name: "Smartphones", slug: "smartphones", parent: "phones-tablets", sortOrder: 1 },
  { name: "Tablets", slug: "tablets", parent: "phones-tablets", sortOrder: 2 },
  { name: "Headphones", slug: "headphones", parent: "audio", sortOrder: 1 },
];

export const seedAttributes: readonly SeedAttribute[] = [
  {
    name: "Colour",
    slug: "colour",
    type: "select",
    isFilterable: true,
    isVariantOption: true,
    sortOrder: 1,
    options: ["Black", "White", "Silver", "Blue", "Red", "Green", "Beige", "Grey"],
  },
  {
    name: "Storage",
    slug: "storage",
    type: "select",
    isFilterable: true,
    isVariantOption: true,
    sortOrder: 2,
    options: ["64GB", "128GB", "256GB", "512GB", "1TB"],
  },
  {
    name: "RAM",
    slug: "ram",
    type: "select",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 3,
    options: ["4GB", "6GB", "8GB", "12GB", "16GB", "32GB"],
  },
  {
    name: "Screen Size",
    slug: "screen-size",
    type: "number",
    unit: "in",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 4,
  },
  {
    name: "Operating System",
    slug: "operating-system",
    type: "select",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 5,
    options: ["Android", "iOS", "Windows", "macOS"],
  },
  {
    name: "5G",
    slug: "five-g",
    type: "boolean",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 6,
  },
  {
    name: "Material",
    slug: "material",
    type: "select",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 7,
    options: ["Wood", "Metal", "Fabric", "Leather", "Glass", "Plastic", "Cotton"],
  },
  {
    name: "Room",
    slug: "room",
    type: "select",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 8,
    options: ["Living Room", "Bedroom", "Office", "Kitchen"],
  },
  {
    name: "Assembly Required",
    slug: "assembly-required",
    type: "boolean",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 9,
  },
  {
    name: "Size",
    slug: "clothing-size",
    type: "select",
    isFilterable: true,
    isVariantOption: true,
    sortOrder: 10,
    options: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    name: "Shoe Size",
    slug: "shoe-size",
    type: "select",
    isFilterable: true,
    isVariantOption: true,
    sortOrder: 11,
    options: ["39", "40", "41", "42", "43", "44", "45"],
  },
  {
    name: "Skin Type",
    slug: "skin-type",
    type: "select",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 12,
    options: ["Oily", "Dry", "Combination", "Sensitive", "All Skin Types"],
  },
  {
    name: "Volume",
    slug: "volume",
    type: "number",
    unit: "ml",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 13,
  },
  {
    name: "Power",
    slug: "power",
    type: "number",
    unit: "W",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 14,
  },
  {
    name: "Capacity",
    slug: "capacity",
    type: "number",
    unit: "L",
    isFilterable: true,
    isVariantOption: false,
    sortOrder: 15,
  },
];

export const seedCategoryAttributes: Readonly<Record<string, readonly string[]>> = {
  electronics: ["colour"],
  smartphones: ["storage", "ram", "screen-size", "operating-system", "five-g"],
  tablets: ["storage", "screen-size", "operating-system"],
  televisions: ["screen-size"],
  laptops: ["colour", "storage", "ram", "screen-size", "operating-system"],
  monitors: ["screen-size"],
  "computer-accessories": ["colour"],
  consoles: ["colour", "storage"],
  "gaming-accessories": ["colour"],
  "mens-clothing": ["colour", "clothing-size", "material"],
  "womens-clothing": ["colour", "clothing-size", "material"],
  footwear: ["colour", "shoe-size", "material"],
  "office-furniture": ["colour", "material", "room", "assembly-required"],
  "living-room": ["colour", "material", "room", "assembly-required"],
  "kitchen-appliances": ["colour", "power", "capacity"],
  "home-care": ["power"],
  skincare: ["skin-type", "volume"],
  fragrance: ["volume"],
  "fitness-equipment": ["material"],
  sportswear: ["colour", "clothing-size"],
};

export const seedProducts: readonly SeedProduct[] = [
  {
    name: "iPhone 15 Pro",
    brand: "apple",
    category: "smartphones",
    price: 1_450_000,
    compareAt: 1_620_000,
    rating: 4.8,
    ratingCount: 214,
    popularity: 980,
    description:
      "Titanium body, A17 Pro chip and a 48MP main camera. Sold with the standard one-year warranty.",
    attributes: {
      ram: "8GB",
      "screen-size": 6,
      "operating-system": "iOS",
      "five-g": true,
    },
    variantAttribute: "storage",
    variantValues: ["128GB", "256GB", "512GB"],
    stock: [12, 7, 0],
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    brand: "samsung",
    category: "smartphones",
    price: 1_380_000,
    rating: 4.7,
    ratingCount: 168,
    popularity: 910,
    description:
      "Built-in S Pen, 200MP camera and a 6.8-inch display with an adaptive refresh rate.",
    attributes: {
      ram: "12GB",
      "screen-size": 6,
      "operating-system": "Android",
      "five-g": true,
    },
    variantAttribute: "storage",
    variantValues: ["256GB", "512GB", "1TB"],
    stock: [9, 4, 2],
  },
  {
    name: "Tecno Camon 30",
    brand: "tecno",
    category: "smartphones",
    price: 285_000,
    compareAt: 320_000,
    rating: 4.2,
    ratingCount: 341,
    popularity: 760,
    description: "Large AMOLED display and a 50MP selfie camera at a mid-range price.",
    attributes: {
      ram: "8GB",
      "screen-size": 6,
      "operating-system": "Android",
      "five-g": false,
    },
    variantAttribute: "storage",
    variantValues: ["128GB", "256GB"],
    stock: [40, 18],
  },
  {
    name: "Infinix Note 40 Pro",
    brand: "infinix",
    category: "smartphones",
    price: 245_000,
    rating: 4.1,
    ratingCount: 289,
    popularity: 705,
    description: "Fast 70W charging with a 5,000mAh battery and a 108MP main sensor.",
    attributes: {
      ram: "8GB",
      "screen-size": 6,
      "operating-system": "Android",
      "five-g": false,
    },
    variantAttribute: "storage",
    variantValues: ["256GB"],
    stock: 55,
  },
  {
    name: "Xiaomi Redmi Note 13",
    brand: "xiaomi",
    category: "smartphones",
    price: 198_000,
    compareAt: 225_000,
    rating: 4.3,
    ratingCount: 402,
    popularity: 820,
    description: "A dependable everyday phone with a 120Hz AMOLED screen.",
    attributes: {
      ram: "6GB",
      "screen-size": 6,
      "operating-system": "Android",
      "five-g": false,
    },
    variantAttribute: "storage",
    variantValues: ["128GB", "256GB"],
    stock: [33, 21],
  },
  {
    name: "iPhone 13",
    brand: "apple",
    category: "smartphones",
    price: 740_000,
    rating: 4.6,
    ratingCount: 512,
    popularity: 690,
    description: "The A15 Bionic chip and a dual-camera system in a compact body.",
    attributes: {
      ram: "4GB",
      "screen-size": 6,
      "operating-system": "iOS",
      "five-g": true,
    },
    variantAttribute: "storage",
    variantValues: ["128GB", "256GB"],
    stock: [6, 0],
  },

  {
    name: 'iPad Air 11"',
    brand: "apple",
    category: "tablets",
    price: 890_000,
    rating: 4.7,
    ratingCount: 96,
    popularity: 540,
    description:
      "M2 chip, Apple Pencil Pro support and an 11-inch Liquid Retina display.",
    attributes: { "screen-size": 11, "operating-system": "iOS" },
    variantAttribute: "storage",
    variantValues: ["128GB", "256GB"],
    stock: [8, 5],
  },
  {
    name: "Samsung Galaxy Tab S9 FE",
    brand: "samsung",
    category: "tablets",
    price: 520_000,
    compareAt: 585_000,
    rating: 4.4,
    ratingCount: 74,
    popularity: 430,
    description:
      "Water-resistant tablet with an included S Pen and a 10.9-inch screen.",
    attributes: { "screen-size": 10, "operating-system": "Android" },
    variantAttribute: "storage",
    variantValues: ["128GB", "256GB"],
    stock: [14, 6],
  },

  {
    name: "Sony WH-1000XM5",
    brand: "sony",
    category: "headphones",
    price: 425_000,
    compareAt: 480_000,
    rating: 4.9,
    ratingCount: 187,
    popularity: 870,
    description: "Industry-leading noise cancellation with 30 hours of battery life.",
    variantAttribute: "colour",
    variantValues: ["Black", "Silver"],
    stock: [11, 4],
  },
  {
    name: "JBL Tune 770NC",
    brand: "jbl",
    category: "headphones",
    price: 135_000,
    rating: 4.3,
    ratingCount: 233,
    popularity: 620,
    description: "Adaptive noise cancelling over-ear headphones with JBL Pure Bass.",
    variantAttribute: "colour",
    variantValues: ["Black", "Blue", "White"],
    stock: [25, 12, 9],
  },
  {
    name: "Anker Soundcore Life Q30",
    brand: "anker",
    category: "headphones",
    price: 78_000,
    compareAt: 92_000,
    rating: 4.2,
    ratingCount: 508,
    popularity: 700,
    description: "Hybrid active noise cancelling with 40-hour playtime.",
    variantAttribute: "colour",
    variantValues: ["Black", "Blue"],
    stock: [48, 30],
  },

  {
    name: 'Hisense 55" 4K UHD Smart TV',
    brand: "hisense",
    category: "televisions",
    price: 620_000,
    compareAt: 715_000,
    rating: 4.3,
    ratingCount: 128,
    popularity: 580,
    description: "4K resolution with Dolby Vision and built-in streaming apps.",
    attributes: { "screen-size": 55 },
    stock: 15,
  },
  {
    name: 'LG 65" OLED evo C4',
    brand: "lg",
    category: "televisions",
    price: 2_150_000,
    rating: 4.8,
    ratingCount: 61,
    popularity: 490,
    description: "Self-lit OLED pixels, 144Hz refresh rate and the α9 AI processor.",
    attributes: { "screen-size": 65 },
    stock: 4,
  },
  {
    name: 'Samsung 43" Crystal UHD',
    brand: "samsung",
    category: "televisions",
    price: 420_000,
    rating: 4.1,
    ratingCount: 204,
    popularity: 520,
    description: "Crystal Processor 4K with slim bezels for smaller rooms.",
    attributes: { "screen-size": 43 },
    stock: 22,
  },

  {
    name: 'MacBook Air 13" M3',
    brand: "apple",
    category: "laptops",
    price: 1_620_000,
    rating: 4.8,
    ratingCount: 143,
    popularity: 940,
    description: "Fanless M3 laptop with up to 18 hours of battery life.",
    attributes: { ram: "8GB", "screen-size": 13, "operating-system": "macOS" },
    variantAttribute: "storage",
    variantValues: ["256GB", "512GB"],
    stock: [10, 5],
  },
  {
    name: "Dell XPS 14",
    brand: "dell",
    category: "laptops",
    price: 1_890_000,
    compareAt: 2_050_000,
    rating: 4.5,
    ratingCount: 58,
    popularity: 610,
    description:
      "InfinityEdge display with a Core Ultra processor and a machined chassis.",
    attributes: { ram: "16GB", "screen-size": 14, "operating-system": "Windows" },
    variantAttribute: "storage",
    variantValues: ["512GB", "1TB"],
    stock: [6, 3],
  },
  {
    name: "HP Pavilion 15",
    brand: "hp",
    category: "laptops",
    price: 680_000,
    compareAt: 760_000,
    rating: 4.0,
    ratingCount: 176,
    popularity: 560,
    description: "A practical everyday laptop for study and office work.",
    attributes: { ram: "8GB", "screen-size": 15, "operating-system": "Windows" },
    variantAttribute: "storage",
    variantValues: ["512GB"],
    stock: 19,
  },
  {
    name: "Lenovo IdeaPad Slim 3",
    brand: "lenovo",
    category: "laptops",
    price: 495_000,
    rating: 4.1,
    ratingCount: 231,
    popularity: 600,
    description: "Lightweight 15-inch laptop with a full-size keyboard.",
    attributes: { ram: "8GB", "screen-size": 15, "operating-system": "Windows" },
    variantAttribute: "storage",
    variantValues: ["256GB", "512GB"],
    stock: [24, 13],
  },
  {
    name: "Asus ROG Strix G16",
    brand: "asus",
    category: "laptops",
    price: 2_340_000,
    rating: 4.6,
    ratingCount: 47,
    popularity: 520,
    description: "RTX graphics and a 165Hz display for gaming and creative work.",
    attributes: { ram: "16GB", "screen-size": 16, "operating-system": "Windows" },
    variantAttribute: "storage",
    variantValues: ["1TB"],
    stock: 5,
  },

  {
    name: 'Dell UltraSharp 27" 4K',
    brand: "dell",
    category: "monitors",
    price: 720_000,
    rating: 4.7,
    ratingCount: 52,
    popularity: 380,
    description: "Colour-accurate IPS Black panel with USB-C power delivery.",
    attributes: { "screen-size": 27 },
    stock: 9,
  },
  {
    name: 'LG UltraGear 24" 144Hz',
    brand: "lg",
    category: "monitors",
    price: 285_000,
    compareAt: 330_000,
    rating: 4.4,
    ratingCount: 118,
    popularity: 470,
    description: "Fast 144Hz gaming monitor with 1ms response time.",
    attributes: { "screen-size": 24 },
    stock: 17,
  },

  {
    name: "Logitech MX Master 3S",
    brand: "logitech",
    category: "computer-accessories",
    price: 148_000,
    rating: 4.8,
    ratingCount: 296,
    popularity: 810,
    description:
      "Quiet-click wireless mouse with an 8K DPI sensor and MagSpeed scrolling.",
    variantAttribute: "colour",
    variantValues: ["Black", "Grey"],
    stock: [21, 14],
  },
  {
    name: "Anker 65W GaN Charger",
    brand: "anker",
    category: "computer-accessories",
    price: 42_000,
    compareAt: 52_000,
    rating: 4.6,
    ratingCount: 445,
    popularity: 740,
    description: "Compact three-port charger that powers a laptop and two phones.",
    variantAttribute: "colour",
    variantValues: ["Black", "White"],
    stock: [60, 45],
  },
  {
    name: "Logitech K380 Keyboard",
    brand: "logitech",
    category: "computer-accessories",
    price: 46_000,
    rating: 4.4,
    ratingCount: 187,
    popularity: 520,
    description: "Multi-device Bluetooth keyboard that switches between three devices.",
    variantAttribute: "colour",
    variantValues: ["Black", "White", "Blue"],
    stock: [30, 22, 0],
  },

  {
    name: "PlayStation 5 Slim",
    brand: "sony",
    category: "consoles",
    price: 890_000,
    rating: 4.8,
    ratingCount: 176,
    popularity: 960,
    description: "Disc edition with the DualSense controller and 3D audio.",
    attributes: { colour: "White" },
    variantAttribute: "storage",
    variantValues: ["1TB"],
    stock: 7,
  },
  {
    name: "Xbox Series X",
    brand: "microsoft",
    category: "consoles",
    price: 840_000,
    compareAt: 920_000,
    rating: 4.7,
    ratingCount: 132,
    popularity: 880,
    description: "4K gaming at up to 120fps with Quick Resume.",
    attributes: { colour: "Black" },
    variantAttribute: "storage",
    variantValues: ["1TB"],
    stock: 5,
  },
  {
    name: "Xbox Series S",
    brand: "microsoft",
    category: "consoles",
    price: 460_000,
    rating: 4.4,
    ratingCount: 208,
    popularity: 690,
    description: "All-digital compact console for 1440p gaming.",
    attributes: { colour: "White" },
    variantAttribute: "storage",
    variantValues: ["512GB"],
    stock: 12,
  },

  {
    name: "DualSense Wireless Controller",
    brand: "sony",
    category: "gaming-accessories",
    price: 118_000,
    rating: 4.6,
    ratingCount: 322,
    popularity: 750,
    description: "Haptic feedback and adaptive triggers for PlayStation 5.",
    variantAttribute: "colour",
    variantValues: ["White", "Black", "Red"],
    stock: [26, 19, 8],
  },
  {
    name: "Logitech G435 Gaming Headset",
    brand: "logitech",
    category: "gaming-accessories",
    price: 72_000,
    compareAt: 85_000,
    rating: 4.2,
    ratingCount: 164,
    popularity: 480,
    description: "Lightweight wireless headset with dual beamforming microphones.",
    variantAttribute: "colour",
    variantValues: ["Black", "Blue"],
    stock: [18, 11],
  },

  {
    name: "Nike Sportswear Club Hoodie",
    brand: "nike",
    category: "mens-clothing",
    price: 68_000,
    compareAt: 82_000,
    rating: 4.5,
    ratingCount: 289,
    popularity: 720,
    description: "Brushed-back fleece hoodie with a kangaroo pocket.",
    attributes: { material: "Cotton", colour: "Black" },
    variantAttribute: "clothing-size",
    variantValues: ["S", "M", "L", "XL"],
    stock: [14, 26, 22, 9],
  },
  {
    name: "Adidas Essentials Track Jacket",
    brand: "adidas",
    category: "mens-clothing",
    price: 74_000,
    rating: 4.3,
    ratingCount: 152,
    popularity: 560,
    description: "Classic three-stripe track jacket in recycled polyester.",
    attributes: { material: "Fabric", colour: "Blue" },
    variantAttribute: "clothing-size",
    variantValues: ["M", "L", "XL"],
    stock: [17, 20, 6],
  },
  {
    name: "Zara Slim Fit Oxford Shirt",
    brand: "zara",
    category: "mens-clothing",
    price: 38_000,
    rating: 4.0,
    ratingCount: 97,
    popularity: 410,
    description: "Cotton oxford shirt with a button-down collar.",
    attributes: { material: "Cotton", colour: "White" },
    variantAttribute: "clothing-size",
    variantValues: ["S", "M", "L"],
    stock: [12, 18, 15],
  },

  {
    name: "Zara Ribbed Knit Midi Dress",
    brand: "zara",
    category: "womens-clothing",
    price: 52_000,
    compareAt: 64_000,
    rating: 4.4,
    ratingCount: 143,
    popularity: 640,
    description: "Fitted ribbed knit dress with a round neckline.",
    attributes: { material: "Fabric", colour: "Beige" },
    variantAttribute: "clothing-size",
    variantValues: ["XS", "S", "M", "L"],
    stock: [8, 16, 19, 11],
  },
  {
    name: "Nike Dri-FIT One Leggings",
    brand: "nike",
    category: "womens-clothing",
    price: 46_000,
    rating: 4.6,
    ratingCount: 318,
    popularity: 690,
    description: "High-waisted training leggings with sweat-wicking fabric.",
    attributes: { material: "Fabric", colour: "Black" },
    variantAttribute: "clothing-size",
    variantValues: ["XS", "S", "M", "L", "XL"],
    stock: [10, 24, 28, 17, 5],
  },

  {
    name: "Nike Air Force 1 '07",
    brand: "nike",
    category: "footwear",
    price: 132_000,
    rating: 4.7,
    ratingCount: 604,
    popularity: 930,
    description: "The original basketball silhouette in full-grain leather.",
    attributes: { material: "Leather", colour: "White" },
    variantAttribute: "shoe-size",
    variantValues: ["40", "41", "42", "43", "44"],
    stock: [6, 14, 18, 12, 4],
  },
  {
    name: "Adidas Samba OG",
    brand: "adidas",
    category: "footwear",
    price: 128_000,
    compareAt: 145_000,
    rating: 4.6,
    ratingCount: 421,
    popularity: 900,
    description: "Low-profile leather trainers with a gum outsole.",
    attributes: { material: "Leather", colour: "Black" },
    variantAttribute: "shoe-size",
    variantValues: ["40", "41", "42", "43"],
    stock: [9, 11, 0, 7],
  },
  {
    name: "Adidas Ultraboost Light",
    brand: "adidas",
    category: "footwear",
    price: 186_000,
    rating: 4.5,
    ratingCount: 178,
    popularity: 660,
    description: "Responsive running shoe with Light BOOST cushioning.",
    attributes: { material: "Fabric", colour: "Grey" },
    variantAttribute: "shoe-size",
    variantValues: ["41", "42", "43", "44"],
    stock: [8, 13, 10, 5],
  },

  {
    name: "Ikea Markus Office Chair",
    brand: "ikea",
    category: "office-furniture",
    price: 245_000,
    compareAt: 285_000,
    rating: 4.4,
    ratingCount: 212,
    popularity: 580,
    description: "High-back mesh office chair with built-in lumbar support.",
    attributes: {
      material: "Fabric",
      room: "Office",
      "assembly-required": true,
      colour: "Black",
    },
    stock: 16,
  },
  {
    name: "Ikea Bekant Desk 160x80",
    brand: "ikea",
    category: "office-furniture",
    price: 320_000,
    rating: 4.2,
    ratingCount: 88,
    popularity: 420,
    description: "Sit-stand capable desk frame with a scratch-resistant top.",
    attributes: {
      material: "Wood",
      room: "Office",
      "assembly-required": true,
      colour: "White",
    },
    stock: 7,
  },
  {
    name: "Ikea Alex Drawer Unit",
    brand: "ikea",
    category: "office-furniture",
    price: 138_000,
    rating: 4.3,
    ratingCount: 134,
    popularity: 390,
    description: "Five-drawer storage unit that fits under most desks.",
    attributes: {
      material: "Wood",
      room: "Office",
      "assembly-required": true,
      colour: "White",
    },
    stock: 11,
  },

  {
    name: "Ikea Kivik 3-Seat Sofa",
    brand: "ikea",
    category: "living-room",
    price: 780_000,
    compareAt: 890_000,
    rating: 4.5,
    ratingCount: 97,
    popularity: 510,
    description: "Deep-seated three-seat sofa with removable, washable covers.",
    attributes: {
      material: "Fabric",
      room: "Living Room",
      "assembly-required": true,
      colour: "Grey",
    },
    stock: 3,
  },
  {
    name: "Ikea Lack Coffee Table",
    brand: "ikea",
    category: "living-room",
    price: 42_000,
    rating: 3.9,
    ratingCount: 268,
    popularity: 450,
    description: "Lightweight coffee table with a hollow-core top.",
    attributes: {
      material: "Wood",
      room: "Living Room",
      "assembly-required": true,
      colour: "Black",
    },
    stock: 34,
  },
  {
    name: "Ikea Poang Armchair",
    brand: "ikea",
    category: "living-room",
    price: 195_000,
    rating: 4.4,
    ratingCount: 156,
    popularity: 470,
    description: "Bentwood frame armchair with a resilient layer-glued seat.",
    attributes: {
      material: "Wood",
      room: "Living Room",
      "assembly-required": true,
      colour: "Beige",
    },
    stock: 0,
  },

  {
    name: "Binatone 1.7L Electric Kettle",
    brand: "binatone",
    category: "kitchen-appliances",
    price: 34_000,
    compareAt: 42_000,
    rating: 4.1,
    ratingCount: 302,
    popularity: 610,
    description: "Rapid-boil stainless steel kettle with automatic shut-off.",
    attributes: { power: 2200, capacity: 2, colour: "Silver" },
    stock: 45,
  },
  {
    name: "Binatone Blender BLG-450",
    brand: "binatone",
    category: "kitchen-appliances",
    price: 58_000,
    rating: 4.0,
    ratingCount: 187,
    popularity: 540,
    description: "Two-speed blender with a grinder attachment and glass jar.",
    attributes: { power: 450, capacity: 2, colour: "White" },
    stock: 28,
  },
  {
    name: "LG 190L Single Door Refrigerator",
    brand: "lg",
    category: "kitchen-appliances",
    price: 465_000,
    compareAt: 520_000,
    rating: 4.3,
    ratingCount: 76,
    popularity: 490,
    description: "Smart inverter compressor with a 10-year warranty.",
    attributes: { power: 120, capacity: 190, colour: "Silver" },
    stock: 8,
  },

  {
    name: "LG CordZero Stick Vacuum",
    brand: "lg",
    category: "home-care",
    price: 520_000,
    rating: 4.5,
    ratingCount: 64,
    popularity: 380,
    description: "Cordless vacuum with two removable batteries.",
    attributes: { power: 590 },
    stock: 6,
  },
  {
    name: 'Binatone Standing Fan 18"',
    brand: "binatone",
    category: "home-care",
    price: 48_000,
    rating: 3.9,
    ratingCount: 219,
    popularity: 430,
    description: "Three-speed standing fan with adjustable height and oscillation.",
    attributes: { power: 60 },
    stock: 37,
  },

  {
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand: "the-ordinary",
    category: "skincare",
    price: 14_500,
    rating: 4.5,
    ratingCount: 812,
    popularity: 850,
    description: "High-strength serum that targets blemishes and congestion.",
    attributes: { "skin-type": "Oily", volume: 30 },
    stock: 120,
  },
  {
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    brand: "the-ordinary",
    category: "skincare",
    price: 15_800,
    compareAt: 18_000,
    rating: 4.4,
    ratingCount: 645,
    popularity: 790,
    description: "Multi-depth hydration serum for all skin types.",
    attributes: { "skin-type": "All Skin Types", volume: 30 },
    stock: 96,
  },
  {
    name: "Nivea Soft Moisturising Cream",
    brand: "nivea",
    category: "skincare",
    price: 6_800,
    rating: 4.2,
    ratingCount: 1_104,
    popularity: 720,
    description: "Light, non-greasy cream with jojoba oil and vitamin E.",
    attributes: { "skin-type": "Dry", volume: 200 },
    stock: 200,
  },

  {
    name: "Nivea Fresh Natural Deodorant",
    brand: "nivea",
    category: "fragrance",
    price: 5_200,
    rating: 4.1,
    ratingCount: 486,
    popularity: 560,
    description: "48-hour protection with an ocean-fresh scent.",
    attributes: { volume: 150 },
    stock: 180,
  },

  {
    name: "Decathlon Adjustable Dumbbell Set 20kg",
    brand: "decathlon",
    category: "fitness-equipment",
    price: 98_000,
    compareAt: 118_000,
    rating: 4.4,
    ratingCount: 141,
    popularity: 520,
    description: "Two adjustable dumbbells with cast-iron plates and a storage case.",
    attributes: { material: "Metal" },
    stock: 13,
  },
  {
    name: "Decathlon Yoga Mat 8mm",
    brand: "decathlon",
    category: "fitness-equipment",
    price: 22_000,
    rating: 4.2,
    ratingCount: 268,
    popularity: 480,
    description: "Cushioned non-slip mat for floor work and stretching.",
    attributes: { material: "Fabric" },
    stock: 64,
  },

  {
    name: "Nike Dri-FIT Training T-Shirt",
    brand: "nike",
    category: "sportswear",
    price: 32_000,
    rating: 4.3,
    ratingCount: 374,
    popularity: 610,
    description: "Sweat-wicking training tee with a standard fit.",
    attributes: { colour: "Black" },
    variantAttribute: "clothing-size",
    variantValues: ["S", "M", "L", "XL"],
    stock: [20, 32, 27, 12],
  },
  {
    name: "Adidas Tiro 24 Training Shorts",
    brand: "adidas",
    category: "sportswear",
    price: 28_000,
    compareAt: 34_000,
    rating: 4.2,
    ratingCount: 196,
    popularity: 530,
    description: "Lightweight training shorts with mesh side panels.",
    attributes: { colour: "Blue" },
    variantAttribute: "clothing-size",
    variantValues: ["S", "M", "L"],
    stock: [18, 24, 16],
  },
];
